project:
  type: website
  output-dir: docs
website:
  title: "Cuochi senza fuochi co-living"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Discover recipe"
        href: tutorials.qmd
      - text: "Why it works"
        href: jobs.qmd
      - text: "Co-living"
        href: tech.qmd
